### ISSUE TITLE
Where should I report problems with Osprey builds?

### ISSUE THREAD

**Issue by Peque** [moto8916/android_device_motorola_harpia#7]
@sultanqasim @Alberto97 I built `lineageos-15.1` based on your sources. Everything went well apparently, but the camera does not work. Where should I report this or reach out for help?

It seems the issues section in `android_device_motorola_osprey` is closed.

PS: I built it using [this manifest](https://github.com/Peque/manifest). If you are interested I can transfer the repo to your organization, where I think it should be instead. :blush:

**Comment by sultanqasim** [comment]
https://github.com/moto8916/android_device_motorola_msm8916-common/blob/lineage-15.1/lineage.dependencies

You're missing android_external_bson in your manifest

**Comment by sultanqasim** [comment]
These repositories will be going official in a few weeks. The moto8916 organization is just my development staging organization shared with Alberto. The once official, no device manifest is needed, things are fetched automatically based on lineage.dependencies.

**Comment by Peque** [comment]
@sultanqasim Thanks for your help! :blush:

Adding `android_external_bson` in the manifest actually helps. Now the camera app is there and I can open it an make videos or panorama pictures. But I cannot take regular pictures... It says "Unknown error. Closing camera". Any ideas/suggestions?

**Comment by sultanqasim** [comment]
I don’t know what could cause that. I hadn’t heard any complaints about the camera on the build I posted to XDA last weekend. Clean flash maybe?

**Comment by Peque** [comment]
@sultanqasim Yeah, it was a clean flash. :woman_shrugging:

**Comment by Peque** [comment]
@sultanqasim By the way, I was using branch `15.1-new` for vendor. Is that correct?

**Comment by sultanqasim** [comment]
Yes

**Comment by Peque** [comment]
@sultanqasim I am closing this issue. Thanks for your help!

Please tell me if you have any further advise/suggestions on how to proceed to try to fix/debug the camera issue (I do not even know where to start). :blush:

**Comment by sultanqasim** [comment]
Do you have boringssl-compat in your manifest? I think I forgot to put it in lineage.dependencies

**Comment by Peque** [comment]
@sultanqasim [This one](https://github.com/LineageOS/android_external_sony_boringssl-compat/tree/lineage-15.1)? If so, I do not have it in my manifest. Should I?

Could any SSL-related stuff be causing the camera misbehavior?

**Comment by Alberto97** [comment]
Uhm, all these devices use M+ blobs, why do they need boringssl-compat? Also LD preloading it is a bad idea, in the past it messed up certain apps login (among them Facebook iirc). The "shim" way was born exactly for this reason

**Comment by Akianonymus** [comment]
boring ssl is not exactly for functionality of camera, it's for improvement in picture quality ig

**Comment by sultanqasim** [comment]
I need to look into why they were preloading it. As Aki says, it was claimed to improve image quality (maybe some conditional dlsym business?). I picked it but hate the LD_PRELOAD and want to kill it if at all possible. I’m guessing someone didn’t know what library to shim or was having issues making the shim work.

**Comment by Peque** [comment]
@sultanqasim I noticed @althafvly [is adding `android_device_qcom_common` to his manifest with LineageOS 16](https://github.com/MOTO-M8916/device_motorola_msm8916-common/blob/lineage-16.0/lineage.dependencies). Would it make sense to try that in order to "fix" my camera issues? :joy:

I have seen [it was removed recently from your repo](https://github.com/moto8916/android_device_motorola_msm8916-common/commit/30dd521203575c75d551cc5f976bfb87e21e72d8).

**Comment by althafvly** [comment]
@Peque qcom common is no longer useful for us.. because dtbtool has moved to another repo.

**Comment by Peque** [comment]
@sultanqasim Is there an issue/place to track official LineageOS integration of this work? I would love to track progress and/or receive a notification on final integration.

@althafvly Do you plan to integrate your `lineageos-16` work too? :blush:
